server:
  port: 8080

spring:
  application:
    name: shop-vault

  # 1.数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/shop-vault # 数据库名: shop-vault
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_ACCOUNT} # 数据库账号
    password: ${MYSQL_PASSWORD} # 数据库密码

  # 2.Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password: ${REDIS_PASSWORD} # Redis密码

  # 3.文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

  mail:
    host: smtp.qq.com
    port: 465
    username: ${QQ_MAIL_ACCOUNT} # QQ 邮箱
    password: ${QQ_MAIL_AUTHORIZATION} # 授权码
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true # QQ 邮箱要求使用 SSL
          auth: true


# 4.MyBatis Plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml # MapperXML扫描路径
  type-aliases-package: com.TsukasaChan.ShopVault.entity # 实体类包别名
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启SQL打印，方便调试
    map-underscore-to-camel-case: true # 开启下划线转驼峰


# 5.自定义配置(供代码读取)
shop-vault:
  jwt:
    secret: shopvault_secret_key_2026_grad_project_secret # JWT密钥
    expiration: 3600000 # 3600000毫秒(1小时)
  YOLO:
    url: http://localhost:5000/predict # Python YOLO服务的地址


# 6. 日志级别
logging:
  level:
    com.shopvault: debug
    org.springframework: info


aliyun:
  oss:
    endpoint: oss-cn-shenzhen.aliyuncs.com # Bucket所在地域Endpoint
    accessKeyId: ${OSS_ACCESS_KEY_ID} # 从环境变量读取
    accessKeySecret: ${OSS_ACCESS_KEY_SECRET}
    bucketName: graduation-design-project1 # 替换为你的Bucket名